# Potential overrides that can be moved to "unify-custom-config.yaml" and read
# by the start scripts.
---
#
# Bigtable
#

TAMR_REMOTE_HBASE_ENABLED: true
TAMR_HBASE_NAMESPACE: ns0
TAMR_HBASE_COMPRESSION: none
TAMR_CONNECTION_INFO_TYPE: bigtable
TAMR_BIGTABLE_EXTRA_CONFIG: "{}"
TAMR_BIGTABLE_PROJECT_ID: tamr-internal-scale
TAMR_BIGTABLE_INSTANCE_ID: internal-scale-dev
TAMR_BIGTABLE_CLUSTER_ID:  internal-scale-dev-b
TAMR_BIGTABLE_SCALING_ENABLED: true
TAMR_BIGTABLE_DOWNSCALE_DELAY: 1

TAMR_HBASE_STORAGE_MODE: SHARED
TAMR_HBASE_NUMBER_OF_REGIONS: 10
TAMR_HBASE_NUMBER_OF_SALT_VALUES: 600
TAMR_BIGTABLE_MIN_NODES: 1
TAMR_BIGTABLE_MAX_NODES: 10
TAMR_HBASE_BATCH_SIZE: 100000
TAMR_HBASE_KEY_SPACE: SALT_AND_PREFIX

#
# Spark
#

TAMR_REMOTE_SPARK_ENABLED: true
TAMR_JOB_SPARK_CLUSTER: dataproc-ephemeral
TAMR_JOB_DATAPROC_CLUSTER_NAME: tamr
TAMR_JOB_DATAPROC_PROJECT_ID: tamr-internal-scale
TAMR_JOB_DATAPROC_REGION: us-east1
TAMR_JOB_DATAPROC_CLUSTER_CONFIG: |
  configBucket: tamr-internal-scale-dataproc-home
  gceClusterConfig:
    zoneUri: us-east1-b
    subnetworkUri: projects/tamr-networking/regions/us-east1/subnetworks/tamr-internal-scale-us-east1
    internalIpOnly: true
    serviceAccount: tsc-instance@tamr-internal-scale.iam.gserviceaccount.com
    metadata:
      signalfx-token: PEC-GICXcfFVKPtFcpSd8w
      solarwinds-token: Zfw_ViMoRHi2_N5cwk9Z--cMO-TTOk5os6uFRcI4LlW6jth3FOtMtYyMm1KMnq0kDyLwCio
      gcs-connector-url: gs://tamr-internal-scale-dataproc-home/jars/java-nio-pipe-gcs-connector-hadoop2-2.2.0-SNAPSHOT-shaded.jar
  initializationActions:
    - executableFile: gs://tamr-dataproc-init/tamr-signalfx/signalfx-agent.sh
      executionTimeout: 500s
    - executableFile: gs://tamr-dataproc-init/fluentd-loggly-dev.sh
      executionTimeout: 500s
    - executableFile: gs://goog-dataproc-initialization-actions-us-east1/connectors/connectors.sh
      executionTimeout: 500s
  softwareConfig:
    imageVersion: 1.3
    properties:
      dataproc:job.history.to-gcs.enabled: true
      dataproc:dataproc.logging.stackdriver.enable: true
      dataproc:dataproc.logging.stackdriver.job.driver.enable: true
      dataproc:dataproc.logging.stackdriver.job.yarn.container.enable: true
      core:fs.gs.outputstream.type: FLUSHABLE_COMPOSITE
      core:fs.gs.outputstream.sync.min.interval.ms: 1500
      core:fs.gs.outputstream.pipe.type: NIO_CHANNEL_PIPE
  masterConfig:
    numInstances: 1
    machineTypeUri: n1-highmem-4
    instanceNames:
      - ephemeral-master
    diskConfig:
      bootDiskType: pd-standard
      bootDiskSizeGb: 1000
  workerConfig:
    numInstances: 4
    machineTypeUri: n1-standard-16
    diskConfig:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
      numLocalSsds: 2
  secondaryWorkerConfig:
    isPreemptible: true
    numInstances: 0
    machineTypeUri: n1-standard-16
    diskConfig:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
      numLocalSsds: 2
TAMR_JOB_SPARK_DRIVER_MEM: 12G
TAMR_JOB_SPARK_EXECUTOR_CORES: 5
TAMR_JOB_SPARK_EXECUTOR_MEM: 13G
TAMR_JOB_SPARK_EXECUTOR_INSTANCES: 12
TAMR_JOB_SPARK_PROPS: |
    {
      'spark.dynamicAllocation.enabled':'false',
      'spark.driver.memoryOverhead':'3072',
      'spark.executor.memoryOverhead':'2048',
      'spark.executor.extraJavaOptions':'-Djdk.nio.maxCachedBufferSize=262144',
      'spark.driver.maxResultSize':'8g',
      'spark.task.maxFailures':'50',
      'spark.stage.maxConsecutiveAttempts':'10',
      'spark.sql.shuffle.partitions':'3100',
      'spark.default.parallelism':'2900',
    }
TAMR_JOB_SPARK_EVENT_LOGS_DIR: gs://tamr-internal-scale-dataproc-home/spark-events
TAMR_MAX_ROWS_PER_PARTITION: 50000

#
# Cloud SQL (PostgreSQL)
#

TAMR_PERSISTENCE_DB_URL: jdbc:postgresql://google/doit?ssl=false&socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=tamr-internal-scale:us-east1:tamr-dev-v1
TAMR_PERSISTENCE_DB_PASS: lV5zn969RHlqGJ0p

#
# Elasticsearch
#

TAMR_ES_ENABLED: true
TAMR_REMOTE_ES_ENABLED: true
TAMR_UNIFY_BACKUP_ES: true
TAMR_ES_APIHOST: es-int-scale.unifydev.xyz:443
TAMR_ES_NETWORK_HOST: _site_
TAMR_ES_USER: tamr
TAMR_ES_PASSWORD: gr8people
TAMR_ES_SSL_ENABLED: true
TAMR_ES_INDEX_NUMBER_OF_SHARDS: 5
TAMR_ES_SOCKET_TIMEOUT: 30000
TAMR_ES_INDEX_STATIC_SETTINGS: |
  index.number_of_shards: 5
  index.translog.sync_interval: 300s
TAMR_ES_INDEX_DYNAMIC_SETTINGS: |
  index.number_of_replicas: 0
  index.mapping.total_fields.limit: 1000000
  index.refresh_interval: 300s
  index.merge.scheduler.max_thread_count: 8
  index.translog.durability: async
  index.translog.flush_threshold_size: 1gb

#
# Logging
#

TAMR_LOG_JSON_ENABLED: false

#
# Filesystem
#

TAMR_FS_URI: gs://tamr-internal-scale-tamr-home
TAMR_FS_KERBEROS_ENABLED: false
TAMR_BACKUP_FS_KERBEROS_ENABLED: false
TAMR_UNIFY_DATA_DIR: gs://tamr-internal-scale-tamr-home/001/unify-data
TAMR_UNIFY_BACKUP_URI: gs://tamr-internal-scale-tamr-home/001/backups

TAMR_STORAGE_PROVIDERS: |
        [{ name: tamr-datasets, description: 'Bucket: gs://tamr-datasets', hdfs: { fsUri: gs://tamr-datasets/ }}]


TAMR_LICENSE_KEY: u6LJPra6lYCkLundGspO8SVUnHkF6jN91etGxlYOKaVvKS++HcU2TbBPO0gqHXicUrGqknxbKfMxnQhOJLYOksloXXL21fEjcjfSfXU1fXTspE3aaHH5Kp7GAV76p+FAVD8JNjf+hleU6v/gqBzUQEoayfX6Zk67xpSHljlUahvvmLHBI6UCWec5vknXXmp9yM3PS1lK2i8Mk+2dqEfP36/fuW/LiaJySx2bcfTi8cWIxlErd8O3QSktqwi9QIyIOBtyKRSXKlRtFNzostO1IMFGGQo+Y+yMHoBZ8buyYiM12ygtegZRaGmVn8D9GO+ip5QZHMbCgdORZC2GG5oxtskV9VWK6Hv5fGcfHjFqQ9wIwaZRTowyLLZJFjvWrvWNsjUmhIuzXu6vZU/08ebpwJ/RXzLXoc2hz3EebhITgrWX/B9pKpyz3vYARCJ7udhkiDPM3DjJ13cfX6ntOuiY5X38RIsb+sWTjRFtaF8h1wsQ5SEFxeKLRXCvslNizhsB/vjEyVtJTomJFGlnL6L2wPRIv0HoQ+rtRAjrXBFUKU+ejoHr4625nZRa9hxJbwycl+1S9IIXxKX6lftaRyHXMunEAkjcsoqh4gf6VReVP+be3SIArEarEDLKZW8b5qNfEwlzkGX1ADFJf3fP8D8UJZLIcXIeyqDq1DUj+jSYe+s=
